services:
  frontend-disponibilidad:        # ← cambiar de "frontend"
    container_name: umg_disponibilidad_prod
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: http://10.0.40.10/api/disponibilidad
        REACT_APP_LOGIN_URL: http://10.0.40.10/login
        REACT_APP_LOGIN_ADMIN_URL: http://10.0.40.10/login-admin
        REACT_APP_ID_CICLO: 1
        REACT_APP_ID_JORNADA: 1
    expose:
      - "3000"                    # ← cambiar de 80 a 3000
    environment:
      - NODE_ENV=production