version: "3.8"
services:
  frontend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: http://10.0.40.10/api/disponibilidad
        REACT_APP_LOGIN_URL: http://10.0.40.10/login
        REACT_APP_LOGIN_ADMIN_URL: http://10.0.40.10/login-admin
        REACT_APP_ID_CICLO: 1
        REACT_APP_ID_JORNADA: 1
    container_name: umg_disponibilidad_prod
    expose:
      - "80"
    environment:
      - NODE_ENV=production